"use client";
import { useState } from "react";
import { createClient } from "@/lib/supabase";
import { useRouter } from "next/navigation";

export default function AdminPanel({site,properties,leads}:{site:any,properties:any[],leads:any[]}){
 const[s,setS]=useState(site||{}); const[ps,setPs]=useState(properties||[]); const[ls,setLs]=useState(leads||[]); const[msg,setMsg]=useState(""); const r=useRouter(); const db=createClient();
 async function upload(file:File,bucket:string,prefix:string){
   const fd=new FormData(); fd.append("file",file); fd.append("bucket",bucket); fd.append("prefix",prefix);
   const res=await fetch("/api/upload",{method:"POST",body:fd}); const data=await res.json(); if(!res.ok) throw new Error(data.error||"上传失败"); return data.url as string;
 }
 async function img(field:string,file:File){try{setMsg("上传中…");const u=await upload(file,"site-images",field);setS((x:any)=>({...x,[field]:u}));setMsg("上传成功，请点击“保存网站设置”")}catch(e:any){setMsg(e.message)}}
 async function save(){const{error}=await db.from("site_settings").update({title:s.title,subtitle:s.subtitle,tagline:s.tagline,address:s.address,phone:s.phone,banner_url:s.banner_url,project1:s.project1,project2:s.project2,project3:s.project3,location_image_url:s.location_image_url}).eq("id",1);setMsg(error?error.message:"网站设置已保存")}
 async function add(){const{data,error}=await db.from("properties").insert({title:"新房源",published:true,sort_order:ps.length+1}).select().single();if(error){setMsg(error.message);return}if(data)setPs([...ps,data])}
 async function saveP(p:any){const payload={title:p.title,area:p.area,floor:p.floor,layout:p.layout,bathroom:p.bathroom,description:p.description,cover_url:p.cover_url,published:p.published,sort_order:p.sort_order};const{data,error}=await db.from("properties").update(payload).eq("id",p.id).select().single();if(!error&&data)setPs(ps.map(x=>x.id===p.id?data:x));setMsg(error?error.message:"房源已保存")}
 async function cover(p:any,file:File){try{setMsg("房源封面上传中…");const u=await upload(file,"property-images",`cover-${p.id}`);setPs(ps.map(x=>x.id===p.id?{...x,cover_url:u}:x));setMsg("封面上传成功，请点击“保存”")}catch(e:any){setMsg(e.message)}}
 async function del(id:string){if(!confirm("确定删除？"))return;const{error}=await db.from("properties").delete().eq("id",id);if(error){setMsg(error.message);return}setPs(ps.filter(x=>x.id!==id))}
 async function delLead(id:number){if(!confirm("确定删除这条客户咨询？"))return;const{error}=await db.from("leads").delete().eq("id",id);if(error){setMsg(error.message);return}setLs(ls.filter(x=>x.id!==id))}
 async function out(){await db.auth.signOut();r.push("/admin/login")}
 const labels:any={banner_url:"首页大图",project1:"项目图1",project2:"项目图2",project3:"项目图3",location_image_url:"地理位置图"};
 return <main className="admin"><header className="adminHead"><div><i>CRAFTS TOWER</i><h1>招商内容管理</h1></div><button type="button" className="outline" onClick={out}>退出</button></header>
 <div className="adminGrid">
 <section className="panel"><h2>首页 / 项目 / 地图</h2><div className="form"><input value={s.title||""} placeholder="首页标题" onChange={e=>setS({...s,title:e.target.value})}/><input value={s.subtitle||""} placeholder="副标题" onChange={e=>setS({...s,subtitle:e.target.value})}/><textarea value={s.tagline||""} placeholder="项目介绍" onChange={e=>setS({...s,tagline:e.target.value})}/><input value={s.address||""} placeholder="地址" onChange={e=>setS({...s,address:e.target.value})}/><input value={s.phone||""} placeholder="招商电话" onChange={e=>setS({...s,phone:e.target.value})}/>{Object.keys(labels).map(k=><div className="upload" key={k}><b>{labels[k]}</b><input value={s[k]||""} onChange={e=>setS({...s,[k]:e.target.value})}/><input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&img(k,e.target.files[0])}/>{s[k]&&<img src={s[k]} alt={labels[k]} style={{maxHeight:120,objectFit:"cover"}}/>}</div>)}<button type="button" className="gold" onClick={save}>保存网站设置</button></div></section>
 <section className="panel"><div className="row"><h2>可租房源</h2><button type="button" className="gold" onClick={add}>+ 新增</button></div>{ps.map(p=><div className="edit" key={p.id}><input value={p.title||""} onChange={e=>setPs(ps.map(x=>x.id===p.id?{...x,title:e.target.value}:x))}/><div className="two"><input placeholder="面积" value={p.area||""} onChange={e=>setPs(ps.map(x=>x.id===p.id?{...x,area:e.target.value}:x))}/><input placeholder="楼层" value={p.floor||""} onChange={e=>setPs(ps.map(x=>x.id===p.id?{...x,floor:e.target.value}:x))}/></div><div className="two"><input placeholder="布局" value={p.layout||""} onChange={e=>setPs(ps.map(x=>x.id===p.id?{...x,layout:e.target.value}:x))}/><input placeholder="卫生间" value={p.bathroom||""} onChange={e=>setPs(ps.map(x=>x.id===p.id?{...x,bathroom:e.target.value}:x))}/></div><textarea placeholder="房源介绍" value={p.description||""} onChange={e=>setPs(ps.map(x=>x.id===p.id?{...x,description:e.target.value}:x))}/><div className="upload"><b>房源封面图</b><input value={p.cover_url||""} placeholder="封面图片 URL" onChange={e=>setPs(ps.map(x=>x.id===p.id?{...x,cover_url:e.target.value}:x))}/><input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&cover(p,e.target.files[0])}/>{p.cover_url&&<img src={p.cover_url} alt="房源封面" style={{maxHeight:150,objectFit:"cover"}}/>}</div><label><input type="checkbox" checked={p.published!==false} onChange={e=>setPs(ps.map(x=>x.id===p.id?{...x,published:e.target.checked}:x))}/> 对外展示</label><div className="actions"><button type="button" className="gold" onClick={()=>saveP(p)}>保存</button><button type="button" className="danger" onClick={()=>del(p.id)}>删除</button><a className="outline" href={`/admin/properties/${p.id}`}>管理多图</a></div></div>)}</section>
 </div>
 <section className="panel" style={{width:"min(1160px,calc(100% - 40px))",margin:"22px auto 0"}}><div className="row"><h2>客户咨询</h2><span>{ls.length} 条</span></div>{!ls.length?<div className="empty">暂无客户咨询</div>:<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th style={{textAlign:"left",padding:10}}>时间</th><th style={{textAlign:"left",padding:10}}>姓名</th><th style={{textAlign:"left",padding:10}}>电话</th><th style={{textAlign:"left",padding:10}}>公司</th><th style={{textAlign:"left",padding:10}}>房源</th><th style={{textAlign:"left",padding:10}}>需求</th><th></th></tr></thead><tbody>{ls.map(l=><tr key={l.id} style={{borderTop:"1px solid #29261f"}}><td style={{padding:10}}>{l.created_at?new Date(l.created_at).toLocaleString("zh-CN"):""}</td><td style={{padding:10}}>{l.name}</td><td style={{padding:10}}>{l.phone}</td><td style={{padding:10}}>{l.company||"-"}</td><td style={{padding:10}}>{l.properties?.title||"-"}</td><td style={{padding:10,whiteSpace:"pre-wrap"}}>{l.message||"-"}</td><td style={{padding:10}}><button type="button" className="danger" onClick={()=>delLead(l.id)}>删除</button></td></tr>)}</tbody></table></div>}</section>{msg&&<div className="toast">{msg}</div>}</main>
}
